site_name: "Polarbayes"
repo_url: "https://github.com/dylanhmorris/polarbayes"

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
  - autorefs:
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          inventories:
            - "https://docs.python.org/3/objects.inv"
