name: "Build and deploy website"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  pages: "write"
  id-token: "write"

jobs:
  build-site:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: actions/checkout@v5

    - name: "Setup polarbayes"
      uses: "./.github/actions/setup-polarbayes"

    - name: "Build site"
      run: "uv run mkdocs build"

    - name: "Upload site artifact"
      uses: actions/upload-pages-artifact@v4
      with:
        name: "github-pages"
        path: "site"
        retention-days: "3"

  deploy-site:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }} # test

    runs-on: "ubuntu-latest"
    needs: "build-site"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      - name: "Deploy site to GitHub Pages"
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "github-pages"
          preview: false
          token: "${{ secrets.GITHUB_TOKEN }}"
